#!/bin/bash
# Purpose: Initialize a new Centaur Project (Knowledge-First Structure) with README.
PROJECT_NAME="$1"
if [ -z "$PROJECT_NAME" ]; then echo "❌ Error: Project Name required."; exit 1; fi

LOCAL_ROOT="$HOME/Projects/$PROJECT_NAME"
DRIVE_ROOT="$HOME/Google Drive/My Drive/Projects/$PROJECT_NAME"

echo "🚀 Initializing Centaur Project: $PROJECT_NAME"

# 1. Create V2 Folder Structure
mkdir -p "$LOCAL_ROOT"/{inputs,outputs,notebooks,processing,reflection/logs}
mkdir -p "$LOCAL_ROOT"/knowledge_base   # For concepts, summaries, notes
mkdir -p "$LOCAL_ROOT"/generated_assets # For raw AI exports/snippets

# 2. Create Drive Mirror
mkdir -p "$DRIVE_ROOT"/{inputs,outputs,notebooks,knowledge_base}

# 3. Create Project README (New!)
echo "📝 Generating Project README..."
cat <<MARKDOWN > "$LOCAL_ROOT/README.md"
# $PROJECT_NAME

**Created:** $(date)
**Type:** Centaur V2 Project (Knowledge-First)

## 🧠 Project Structure

### 1. Memory Brain (\`knowledge_base/\`)
Stores the *concepts* learned during this project.
- AI Chat Summaries
- Design Documents
- Reference PDFs

### 2. Execution Brain (\`notebooks/\`)
Where code runs and analysis happens.
- Jupyter Notebooks
- \`generated_assets/\`: Raw scripts or data snippets generated by AI.

### 3. Data Flow
- \`inputs/\`: Raw data sources (Ignored by Git).
- \`outputs/\`: Final results and artifacts.

---
*Managed by Centaur Workflow Tools.*
MARKDOWN

# 4. Git Init
if [ ! -d "$LOCAL_ROOT/.git" ]; then
    git -C "$LOCAL_ROOT" init > /dev/null
    cat <<IGNORE > "$LOCAL_ROOT/.gitignore"
inputs/
outputs/
processing/
generated_assets/
*.log
.DS_Store
__pycache__/
.ipynb_checkpoints/
IGNORE
fi

# 5. Setup Log
LOG_FILE="$LOCAL_ROOT/reflection/logs/setup_$(date +%Y%m%d_%H%M%S).txt"
echo "Project $PROJECT_NAME created (Centaur V2)" > "$LOG_FILE"
echo "🎉 Project setup complete!"
